services:
  - type: web
    name: pitiupi-backend
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name: pitiupi-db
          property: connectionString
      - key: NUVEI_ENV
        value: "prod"          # o stg si tus credenciales son de staging
      - key: NUVEI_APP_CODE_SERVER
        sync: false
      - key: NUVEI_APP_KEY_SERVER
        sync: false
      - key: NUVEI_APP_CODE_CLIENT
        sync: false
      - key: NUVEI_APP_KEY_CLIENT
        sync: false
